//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class finalorder
    {
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Party_date { get; set; }
        [DataType(DataType.Time)]
        public System.TimeSpan Party_time { get; set; }
        public Nullable<decimal> Total_price { get; set; }
    }
}
