//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string id { get; set; }
        public string Pid { get; set; }
        public string Food { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
